# Dockerfile.auth

# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) to install dependencies first
COPY auth/package*.json ./

# Install dependencies
RUN npm ci --legacy-peer-deps

# Copy the rest of the API source code into the container
COPY auth/ .

# Expose the AUTH port
EXPOSE 4000

# Start the API server
CMD ["npm", "run", "dev"]